version: '3'

services:
  db_blog:
    image: postgres
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog
    volumes:
      - db_blog:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_blog:
    driver: local